{% set name = "alibabacloud-gateway-spi" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/alibabacloud_gateway_spi-{{ version }}.tar.gz
  sha256: 10d1c53a3fc5f87915fbd6b4985b98338a776e9b44a0263f56643c5048223b8b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - alibabacloud-credentials >=0.3.4

test:
  imports:
    - alibabacloud_gateway_spi
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/aliyun/alibabacloud-gateway
  summary: Alibaba Cloud Gateway SPI SDK Library for Python
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
