{% set name = "alibabacloud-gateway-spi" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/alibabacloud_gateway_spi-{{ version }}.tar.gz
  sha256: 1b259855708afc3c04d8711d8530c63f7645e1edc0cf97e2fd15461b08e11c30

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - alibabacloud-credentials >=0.2.0,<1.0.0

test:
  imports:
    - alibabacloud_gateway_spi
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aliyun/alibabacloud-gateway
  summary: Alibaba Cloud Gateway SPI SDK Library for Python
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
